version: "3.5"

services:
  mariadb:
    image: mariadb:10.5.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - "$PWD/mariadb/data:/var/lib/mysql"
      - "$PWD/mariadb/log:/var/log/mysql"
      - "$PWD/mariadb/conf:/etc/mysql"

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongo/mongo_data:/data/db"

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    volumes:
      - "$PWD/consul:/consul"

  # jenkins:
  #   image: jenkins/jenkins:latest
  #   restart: always
  #   container_name: jenkins
  #   ports:
  #     - "8080:8080"
  #     - "5000:5000"
  #   volumes:
  #     - "$PWD/jenkins/data:/var/jenkins_home"
  #     - "$PWD/jenkins/run:/var/run"
  #     - "/bin/docker:/bin/docker"
  #   user: root
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app_net

  broker-1:
    image: wurstmeister/kafka:latest
    restart: always
    container_name: broker-1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_NUM_PARTITIONS: 3
    networks:
      - app_net

  # broker-2:
  #   image: wurstmeister/kafka:latest
  #   restart: always
  #   container_name: broker-2
  #   ports:
  #     - "9093:9093"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
  #     KAFKA_CFG_NUM_PARTITIONS: 3
  #   networks:
  #     - app_net

  # broker-3:
  #   image: wurstmeister/kafka:latest
  #   restart: always
  #   container_name: broker-3
  #   ports:
  #     - "9094:9094"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
  #     KAFKA_CFG_NUM_PARTITIONS: 3
  #   networks:
  #     - app_net

  # broker-manager:
  #   image: sheepkiller/kafka-manager:latest
  #   restart: always
  #   container_name: broker-manager
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     ZK_HOSTS: zookeeper:2181
  #     KAFKA_BROKERS: broker-1:9092,broker-2:9093,broker-3:9094
  #   networks:
  #     - app_net

  elasticsearch:
    image: elasticsearch:7.13.3
    container_name: elasticsearch
    privileged: true
    environment: 
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1096m"
      - "bootstrap.memory_lock=true"
    volumes:
      - "$PWD/es/plugins:/usr/share/elasticsearch/plugins"
      - "$PWD/es/data:/usr/share/elasticsearch/data:rw"
      - "$PWD/es/logs:/user/share/elasticsearch/logs:rw"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:7.13.3
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200 #设置访问elasticsearch的地址
      I18N_LOCALE: zh-CN
    ports:
      - "5601:5601"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus/config:/etc/prometheus
      - $PWD/prometheus/data/prometheus_db:/prometheus 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - app_net

  # # 可视化面板
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "$PWD/grafana/data:/var/lib/grafana"
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - app_net

  # # 采用被动推送方式获取数据并推送给prometheus
  # pushgateway:
  #   image: prom/pushgateway
  #   container_name: pushgateway
  #   restart: always
  #   ports:
  #     - "9091:9091"
  #   volumes:
  #     - $PWD/prometheus/data/pushgateway_data:/var/lib/pushgateway

  # # 告警系统
  # alertmanager:
  #   image: prom/alertmanager
  #   hostname: alertmanager
  #   container_name: alertmanager
  #   restart: always
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - $PWD/prometheus/data/alertmanager_data:/var/lib/alertmanager

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 1080:80
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "$PWD/nginx/conf/log:/var/log/nginx"
      - "$PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/conf/html:/usr/share/nginx/html"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
