version: "3.5"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - "./ollama/root:/root/.ollama"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    networks:
      - app-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - "./open-webui:/app/backend/data"
    environment:
      - "HF_ENDPOINT=https://hf-mirror.com"
      - "OLLAMA_BASE_URL=http://ollama:11434"
    depends_on:
      - ollama
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

