# 全局配置  
global:  
  scrape_interval:     15s # 设置默认的抓取间隔为15秒  
  evaluation_interval: 15s # 设置规则评估间隔为15秒  
  
# 抓取配置  
scrape_configs:  
  # Prometheus 自监控  
  - job_name: 'prometheus'  
    static_configs:  
    - targets: ['localhost:9090'] # Prometheus 服务自身的地址和端口  
  
  # 示例：监控 node_exporter  
  - job_name: 'node'  
    static_configs:  
    - targets: ['prometheus-exporter:9100'] # 假设 node_exporter 运行在本地9100端口

  - job_name: 'mongo_exporter'
    static_configs:
    - targets: ['mongo_exporter:9216']
  - job_name: 'python_exporter'
    static_configs:
    - targets: ['host.docker.internal:8080']

